# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dbozic <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/20 14:53:43 by dbozic            #+#    #+#              #
#    Updated: 2024/12/20 14:53:45 by dbozic           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = c++
FLAGS = -Wall -Wextra -Werror -std=c++98
SOURCES = megaphone.cpp
PROGRAM = megaphone

all:
	$(CC) $(FLAGS) $(SOURCES) -o $(PROGRAM)
	
clean:

fclean:
	rm $(PROGRAM)

re: fclean all